//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public string MaBL { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public string MaNV { get; set; }
        public string MaPB { get; set; }
        public long LuongCB { get; set; }
        public long LuongThuong { get; set; }
        public string MaChamCong { get; set; }
        public long PhuCap { get; set; }
        public long TongLuong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
