//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenMon
    {
        public string MaCTCM { get; set; }
        public string MaNV { get; set; }
        public string MaCM { get; set; }
        public System.DateTime NgayCap { get; set; }
        public string Truong { get; set; }
    
        public virtual ChuyenMon ChuyenMon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
