//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKhenThuong
    {
        public string SoQD { get; set; }
        public System.DateTime NgayQD { get; set; }
        public string MaNV { get; set; }
        public string NoiDung { get; set; }
        public string HinhThuc { get; set; }
        public string MaKT { get; set; }
    
        public virtual KhenThuong KhenThuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
