//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenCongTac
    {
        public string MaChuyen { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayChuyen { get; set; }
        public string MaCVCu { get; set; }
        public string MaPBCu { get; set; }
        public string MaCVMoi { get; set; }
        public string MaPBMoi { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
