//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThucTinhLuong
    {
        public int ID { get; set; }
        public string CongThuc { get; set; }
        public int MaLoaiCT { get; set; }
        public long LuongCB { get; set; }
        public long LuongThuong { get; set; }
        public long PhuCap { get; set; }
        public long TongLuong { get; set; }
    
        public virtual LoaiCongThuc LoaiCongThuc { get; set; }
    }
}
