//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BangLuongs = new HashSet<BangLuong>();
            this.BoPhans = new HashSet<BoPhan>();
            this.ChiTietChamCongs = new HashSet<ChiTietChamCong>();
            this.ChiTietChuyenMons = new HashSet<ChiTietChuyenMon>();
            this.ChiTietKiLuats = new HashSet<ChiTietKiLuat>();
            this.ChiTietKhenThuongs = new HashSet<ChiTietKhenThuong>();
            this.ChuyenCongTacs = new HashSet<ChuyenCongTac>();
            this.NguoiDungs = new HashSet<NguoiDung>();
            this.PhongBans = new HashSet<PhongBan>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
        public string MaCV { get; set; }
        public string MaBP { get; set; }
        public string MaPB { get; set; }
        public string MaHD { get; set; }
        public string MaLoaiLuong { get; set; }
        public string MaTTCT { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoPhan> BoPhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChamCong> ChiTietChamCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChuyenMon> ChiTietChuyenMons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKiLuat> ChiTietKiLuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKhenThuong> ChiTietKhenThuongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenCongTac> ChuyenCongTacs { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual LoaiLuong LoaiLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public virtual ThongTinChiTietNhanVien ThongTinChiTietNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongBan> PhongBans { get; set; }
    }
}
